# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspeech.proto\"R\n\x08WordInfo\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\x12\x0c\n\x04word\x18\x03 \x02(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"\x1c\n\rRecognizeTest\x12\x0b\n\x03msg\x18\x01 \x02(\t\"!\n\x11RecognizeTestEcho\x12\x0c\n\x04\x65\x63ho\x18\x01 \x02(\t\" \n\x10RecognizeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\"!\n\x11RecognizeResponse\x12\x0c\n\x04text\x18\x01 \x02(\t\")\n\x19StreamingRecognizeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"*\n\x1aStreamingRecognizeResponse\x12\x0c\n\x04text\x18\x01 \x02(\t2\xba\x01\n\x06Speech\x12\x34\n\tRecognize\x12\x11.RecognizeRequest\x1a\x12.RecognizeResponse\"\x00\x12H\n\x12StreamingRecognize\x12\x1a.StreamingRecognizeRequest\x1a\x12.RecognizeResponse\"\x00(\x01\x12\x30\n\x08\x45\x63hoTest\x12\x0e.RecognizeTest\x1a\x12.RecognizeTestEcho\"\x00')



_WORDINFO = DESCRIPTOR.message_types_by_name['WordInfo']
_RECOGNIZETEST = DESCRIPTOR.message_types_by_name['RecognizeTest']
_RECOGNIZETESTECHO = DESCRIPTOR.message_types_by_name['RecognizeTestEcho']
_RECOGNIZEREQUEST = DESCRIPTOR.message_types_by_name['RecognizeRequest']
_RECOGNIZERESPONSE = DESCRIPTOR.message_types_by_name['RecognizeResponse']
_STREAMINGRECOGNIZEREQUEST = DESCRIPTOR.message_types_by_name['StreamingRecognizeRequest']
_STREAMINGRECOGNIZERESPONSE = DESCRIPTOR.message_types_by_name['StreamingRecognizeResponse']
WordInfo = _reflection.GeneratedProtocolMessageType('WordInfo', (_message.Message,), {
  'DESCRIPTOR' : _WORDINFO,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:WordInfo)
  })
_sym_db.RegisterMessage(WordInfo)

RecognizeTest = _reflection.GeneratedProtocolMessageType('RecognizeTest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZETEST,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:RecognizeTest)
  })
_sym_db.RegisterMessage(RecognizeTest)

RecognizeTestEcho = _reflection.GeneratedProtocolMessageType('RecognizeTestEcho', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZETESTECHO,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:RecognizeTestEcho)
  })
_sym_db.RegisterMessage(RecognizeTestEcho)

RecognizeRequest = _reflection.GeneratedProtocolMessageType('RecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEREQUEST,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:RecognizeRequest)
  })
_sym_db.RegisterMessage(RecognizeRequest)

RecognizeResponse = _reflection.GeneratedProtocolMessageType('RecognizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZERESPONSE,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:RecognizeResponse)
  })
_sym_db.RegisterMessage(RecognizeResponse)

StreamingRecognizeRequest = _reflection.GeneratedProtocolMessageType('StreamingRecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGRECOGNIZEREQUEST,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:StreamingRecognizeRequest)
  })
_sym_db.RegisterMessage(StreamingRecognizeRequest)

StreamingRecognizeResponse = _reflection.GeneratedProtocolMessageType('StreamingRecognizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINGRECOGNIZERESPONSE,
  '__module__' : 'speech_pb2'
  # @@protoc_insertion_point(class_scope:StreamingRecognizeResponse)
  })
_sym_db.RegisterMessage(StreamingRecognizeResponse)

_SPEECH = DESCRIPTOR.services_by_name['Speech']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORDINFO._serialized_start=16
  _WORDINFO._serialized_end=98
  _RECOGNIZETEST._serialized_start=100
  _RECOGNIZETEST._serialized_end=128
  _RECOGNIZETESTECHO._serialized_start=130
  _RECOGNIZETESTECHO._serialized_end=163
  _RECOGNIZEREQUEST._serialized_start=165
  _RECOGNIZEREQUEST._serialized_end=197
  _RECOGNIZERESPONSE._serialized_start=199
  _RECOGNIZERESPONSE._serialized_end=232
  _STREAMINGRECOGNIZEREQUEST._serialized_start=234
  _STREAMINGRECOGNIZEREQUEST._serialized_end=275
  _STREAMINGRECOGNIZERESPONSE._serialized_start=277
  _STREAMINGRECOGNIZERESPONSE._serialized_end=319
  _SPEECH._serialized_start=322
  _SPEECH._serialized_end=508
# @@protoc_insertion_point(module_scope)
